document.writeln('     <div class="container_equip">');
document.writeln('      <div class="menu_container cor_1">');
document.writeln('        <div class="menu_container_cabecalho">');
document.writeln('          <h1>Arma Primaria</h1>');
document.writeln('        </div>');
document.writeln('        <div class="menu_container_blocos">');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Arma I</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">              ');
document.writeln('              <img src="../images/equipamentos/arma1.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>75 - Aço Raro</p>');
document.writeln('              <p>25 - Esfera Perversa</p>');
document.writeln('              <p>25 - Pedra de Sombra</p>');
document.writeln('              <p>Craft - 10k</p>');
document.writeln('              <p>Total - 135K DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Arma II</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/arma2.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>2x ARMA I - 250k</p>');
document.writeln('              <p>Craft - 35k</p>');
document.writeln('              <b>Total - 285k DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Arma III</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/arma3.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>4x ARMA I - 500k</p>');
document.writeln('              <p>2x ARMA II</p>');
document.writeln('              <p>Craft - 90k</p>');
document.writeln('              <b>Total - 590k DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Arma IV</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/arma4.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>8x ARMA I - 1kk</p>');
document.writeln('              <p>4x ARMA II</p>');
document.writeln('              <p>2x ARMA III</p>');
document.writeln('              <p>Craft - 205k</p>');
document.writeln('              <b>Total - 1.205.000 DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('      <div class="menu_container cor_1">');
document.writeln('        <div class="menu_container_cabecalho">');
document.writeln('          <h1>Armadura</h1>');
document.writeln('        </div>');
document.writeln('        <div class="menu_container_blocos">');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Armadura I</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/torso1.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>75 - Aço Raro</p>');
document.writeln('              <p>25 - Quintessencia</p>');
document.writeln('              <p>25 - Bugiganga de Exorcismo</p>');
document.writeln('              <p>Craft - 5k</p>');
document.writeln('              <p>Total - 135K DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Armadura II</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/torso2.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>2x ARMADURA I - 250k</p>');
document.writeln('              <p>Craft - 17.5k</p>');
document.writeln('              <b>Total - 267.5k DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Armadura III</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/torso3.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>4x ARMADURA I - 500k</p>');
document.writeln('              <p>2x ARMADURA II</p>');
document.writeln('              <p>Craft - 45k</p>');
document.writeln('              <b>Total - 545k DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Armadura IV</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/torso4.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>8x ARMADURA I - 1kk</p>');
document.writeln('              <p>4x ARMADURA II</p>');
document.writeln('              <p>2x ARMADURA III</p>');
document.writeln('              <p>Craft - 102.5k</p>');
document.writeln('              <b>Total - 1.102.500 DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('      <div class="menu_container cor_1">');
document.writeln('        <div class="menu_container_cabecalho">');
document.writeln('          <h1>Acessorios</h1>');
document.writeln('        </div>');
document.writeln('        <div class="menu_container_blocos">');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Acessorio I</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/colar1.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>75 - Platina Rara</p>');
document.writeln('              <p>25 - Flagmento Iluminante</p>');
document.writeln('              <p>25 - Pedra de Anima</p>');
document.writeln('              <p>Craft - 10k</p>');
document.writeln('              <b>Total - 135K DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Acessorio II</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/colar2.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>2x ACESSORIO I - 250k</p>');
document.writeln('              <p>Craft - 35k</p>');
document.writeln('              <b>Total - 285k DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Acessorio III</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/colar3.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>4x ACESSORIO I - 500k</p>');
document.writeln('              <p>2x ACESSORIO II</p>');
document.writeln('              <p>Craft - 90k</p>');
document.writeln('              <b>Total - 590k DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Acessorio IV</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/colar4.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>8x ACESSORIO I - 1kk</p>');
document.writeln('              <p>4x ACESSORIO II</p>');
document.writeln('              <p>2x ACESSORIO III</p>');
document.writeln('              <p>Craft - 205k</p>');
document.writeln('              <b>Total - 1.205.000 DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('      <div class="menu_container cor_2">');
document.writeln('        <div class="menu_container_cabecalho">');
document.writeln('          <h1>Arma Primaria</h1>');
document.writeln('        </div>');
document.writeln('        <div class="menu_container_blocos">');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Arma I</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/epica1.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>300 - Aço Heroico</p>');
document.writeln('              <p>100 - Esfera Perversa</p>');
document.writeln('              <p>100 - Pedra de Sombra</p>');
document.writeln('              <p>Craft - 100k</p>');
document.writeln('              <p>Total - 2.600.000 DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Arma II</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/epica2.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>2x ARMA I - 5.000.000</p>');
document.writeln('              <p>Craft - 400k</p>');
document.writeln('              <b>Total - 5.400.000 DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Arma III</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/epica3.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>4x ARMA I - 10.000.000</p>');
document.writeln('              <p>2x ARMA II</p>');
document.writeln('              <p>Craft - 1.000.000</p>');
document.writeln('              <b>Total - 11.000.000</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Arma IV</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/epica4.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>8x ARMA I - 20.000.000</p>');
document.writeln('              <p>4x ARMA II</p>');
document.writeln('              <p>2x ARMA III</p>');
document.writeln('              <p>Craft - 2.600.000</p>');
document.writeln('              <b>Total - 22.600.000 DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('      <div class="menu_container cor_2">');
document.writeln('        <div class="menu_container_cabecalho">');
document.writeln('          <h1>Armadura</h1>');
document.writeln('        </div>');
document.writeln('        <div class="menu_container_blocos">');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Armadura I</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/torso_epico1.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>300 - Aço Raro</p>');
document.writeln('              <p>100 - Quintessencia</p>');
document.writeln('              <p>100 - Bugiganga de Exorcismo</p>');
document.writeln('              <p>Craft - 50k</p>');
document.writeln('              <p>Total - 2.550.000 DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Armadura II</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/torso_epico2.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>2x ARMADURA I - 5.000.000</p>');
document.writeln('              <p>Craft - 200k</p>');
document.writeln('              <p>Total - 5.200.000 DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Armadura III</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/torso_epico3.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>4x ARMADURA I - 10.000.000k</p>');
document.writeln('              <p>2x ARMADURA II</p>');
document.writeln('              <p>Craft - 400k</p>');
document.writeln('              <p>Total - 10.400.000 DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Armadura IV</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/torso_epico4.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>8x ARMADURA I - 20.000.000</p>');
document.writeln('              <p>4x ARMADURA II</p>');
document.writeln('              <p>2x ARMADURA III</p>');
document.writeln('              <p>Craft - 800K</p>');
document.writeln('              <p>Total - 21.100.000 DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('      <div class="menu_container cor_2">');
document.writeln('        <div class="menu_container_cabecalho">');
document.writeln('          <h1>Acessorios</h1>');
document.writeln('        </div>');
document.writeln('        <div class="menu_container_blocos">');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Acessorio I</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/pulseira_epica1.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>300 - Platina Rara</p>');
document.writeln('              <p>100 - Flagmento Iluminante</p>');
document.writeln('              <p>100 - Pedra de Anima</p>');
document.writeln('              <p>Craft - 100k</p>');
document.writeln('              <p>Total - 2.600.000 DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Acessorio II</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/pulseira_epica2.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>2x ACESSORIO I - 5.000.000</p>');
document.writeln('              <p>Craft - 400k</p>');
document.writeln('              <b>Total - 5.400.000 DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Acessorio III</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/pulseira_epica3.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>4x ACESSORIO I - 10.000.000</p>');
document.writeln('              <p>2x ACESSORIO II</p>');
document.writeln('              <p>Craft - 1.000.000</p>');
document.writeln('              <b>Total - 11.000.000</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Acessorio IV</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/pulseira_epica4.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>8x ACESSORIO I - 20.000.000</p>');
document.writeln('              <p>4x ACESSORIO II</p>');
document.writeln('              <p>2x ACESSORIO III</p>');
document.writeln('              <p>Craft - 2.600.000</p>');
document.writeln('              <b>Total - 22.600.000 DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('      <div class="menu_container cor_3">');
document.writeln('        <div class="menu_container_cabecalho">');
document.writeln('          <h1>Arma Primaria</h1>');
document.writeln('        </div>');
document.writeln('        <div class="menu_container_blocos">');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Arma I</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/arma_lendaria1.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>300 - Aço Lendario</p>');
document.writeln('              <p>100 - Esfera Perversa</p>');
document.writeln('              <p>100 - Pedra de Sombra</p>');
document.writeln('              <p>Craft - 1.000.000</p>');
document.writeln('              <p>Total - 13.500.000 DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Arma II</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/arma_lendaria2.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>2x ARMA I - 25.000.000</p>');
document.writeln('              <p>Craft - 4.000.000</p>');
document.writeln('              <b>Total - 29.000.000 DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Arma III</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/arma_lendaria3.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>4x ARMA I - 50.000.000</p>');
document.writeln('              <p>2x ARMA II</p>');
document.writeln('              <p>Craft - 11.000.000</p>');
document.writeln('              <b>Total - 61.000.000</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Arma IV</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/arma_lendaria4.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>8x ARMA I -</p>');
document.writeln('              <p>4x ARMA II</p>');
document.writeln('              <p>2x ARMA III</p>');
document.writeln('              <p>Craft - 26.000.000</p>');
document.writeln('              <b>Total - 126.000.000 DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('      <div class="menu_container cor_3">');
document.writeln('        <div class="menu_container_cabecalho">');
document.writeln('          <h1>Armadura</h1>');
document.writeln('        </div>');
document.writeln('        <div class="menu_container_blocos">');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Armadura I</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/torso_lendario1.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>300 - Aço Raro</p>');
document.writeln('              <p>100 - Quintessencia</p>');
document.writeln('              <p>100 - Bugiganga de Exorcismo</p>');
document.writeln('              <p>Craft - 500k</p>');
document.writeln('              <p>Total - 13.000.000 DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Armadura II</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/torso_lendario2.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>2x ARMADURA I - 25.000.000</p>');
document.writeln('              <p>Craft - 2.000.000</p>');
document.writeln('              <p>Total - 27.000.000 DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Armadura III</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/torso_lendario3.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>4x ARMADURA I - 50.000.000</p>');
document.writeln('              <p>2x ARMADURA II</p>');
document.writeln('              <p>Craft - 5.500.000</p>');
document.writeln('              <p>Total - 55.500.000 DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Armadura IV</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/torso_lendario4.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>8x ARMADURA I - 100.000.000</p>');
document.writeln('              <p>4x ARMADURA II</p>');
document.writeln('              <p>2x ARMADURA III</p>');
document.writeln('              <p>Craft - 13.000.000</p>');
document.writeln('              <p>Total - 113.000.000 DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('      <div class="menu_container cor_3">');
document.writeln('        <div class="menu_container_cabecalho">');
document.writeln('          <h1>Acessorios</h1>');
document.writeln('        </div>');
document.writeln('        <div class="menu_container_blocos">');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Acessorio I</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/anel_lendario1.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>300 - Platina Rara</p>');
document.writeln('              <p>100 - Flagmento Iluminante</p>');
document.writeln('              <p>100 - Pedra de Anima</p>');
document.writeln('              <p>Craft - 1.000.000</p>');
document.writeln('              <p>Total - 13.500.000 DS</p>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Acessorio II</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/anel_lendario2.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>2x ACESSORIO I - 5.000.000</p>');
document.writeln('              <p>Craft - 4.000.000</p>');
document.writeln('              <b>Total - 29.000.000 DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Acessorio III</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/anel_lendario3.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>4x ACESSORIO I - 10.000.000</p>');
document.writeln('              <p>2x ACESSORIO II</p>');
document.writeln('              <p>Craft - 11.000.000</p>');
document.writeln('              <b>Total - 61.000.000</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('          <div class="item">');
document.writeln('            <div class="items_nome">');
document.writeln('              <h2>Acessorio IV</h2>');
document.writeln('            </div>');
document.writeln('            <div class="items_imagem">');
document.writeln('              <img src="../images/equipamentos/anel_lendario4.PNG" alt="" />');
document.writeln('            </div>');
document.writeln('            <div class="items_lista">');
document.writeln('              <p>8x ACESSORIO I - 20.000.000</p>');
document.writeln('              <p>4x ACESSORIO II</p>');
document.writeln('              <p>2x ACESSORIO III</p>');
document.writeln('              <p>Craft - 26.000.000</p>');
document.writeln('              <b>Total - 126.000.000 DS</b>');
document.writeln('            </div>');
document.writeln('          </div>');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('      <div class="menu_container">');
document.writeln('        <h1>Total</h1>');
document.writeln('        <div class="menu_container_blocos">');
document.writeln('        <div class="item">');
document.writeln('          <div class="items_nome">');
document.writeln('            <h2>Aço Negro</h2>');
document.writeln('          </div>');
document.writeln('          <img src="../images/craft/Dark_Steel.png" alt="" />');
document.writeln('          <br>');
document.writeln('          <div class="items_lista total">');
document.writeln('        <p>FULL LVL 4 RARO <br> 8.816.000</p>');
document.writeln('        <p>FULL LVL 4 EPICO <br> 174.000.000</p>');
document.writeln('        <p>FULL LVL 4 LENDARIO <br> 956.000.000</p>');
document.writeln('        </div>');
document.writeln('        </div>');
document.writeln('        <div class="item">');
document.writeln('          <div class="items_nome">');
document.writeln('            <h2>Pó</h2>');
document.writeln('          </div>');
document.writeln('          <div class="items_imagem">');
document.writeln('          <img src="../images/craft/Po.png" alt="" />');
document.writeln('        </div>');
document.writeln('        <br>');
document.writeln('          <div class="items_lista total">');
document.writeln('        <p>FULL LVL 4 RARO <br>16.000</p>');
document.writeln('        <p>FULL LVL 4 EPICO <br>200.000</p>');
document.writeln('        <p>FULL LVL 4 LENDARIO <br>1.000.000</p>');
document.writeln('        </div>');
document.writeln('        </div>');
document.writeln('        <div class="item">');
document.writeln('          <div class="items_nome">');
document.writeln('            <h2>Cobre</h2>');
document.writeln('          </div>');
document.writeln('          <img src="../images/craft/Cobre.png" alt="" />');
document.writeln('          <br>');
document.writeln('          <div class="items_lista total">');
document.writeln('        <p>FULL LVL 4 RARO <br>23.800.000</p>');
document.writeln('        <p>FULL LVL 4 EPICO <br>99.200.000</p>');
document.writeln('        <p>FULL LVL 4 LENDARIO <br>1.560.000.000</p>');
document.writeln('        </div>');
document.writeln('        </div>');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('    </div>');
